# 1. Server Config
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  mvc:
    static-path-pattern: /uploads/**  
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/petgpt?characterEncoding=utf8
    username: root
    password: 1234
  web:
    resources:
      static-locations: file:///C:/petshop/uploads/

# 3. Mybatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 3. Log Level
logging:
  level:
    root: info   #  error < info < debug

# 4. User Define App
app:
  key:
    algo: PBEWithMD5AndDES  # Twoway
    skey: mykey             # Twoway

# 이미지 업로드 디렉토리 및 URL prefix 설정
file:
  upload:
    directory: C:/petshop/uploads/images
    url:
      prefix: /uploads/images

# AI 서비스
chatbot:
  api:
    url: http://127.0.0.1:8000/generate # AI 서비스 API 엔드포인트