# 1. Server Config
server:
  port: 8443  # HTTPS를 위한 포트 설정
  ssl:
    enabled: true
    key-store: classpath:keystore.p12  # 인증서 파일 경로 <- keystore.p12를 resource 아래 위치
    key-store-password: 111111  # 인증서 생성 시 설정한 비밀번호
    key-store-type: PKCS12  # 인증서 형식
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  mvc:
    static-path-pattern: /uploads/**  
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://118.67.143.55:3306/petgpt?characterEncoding=utf8
    username: mcuser
    password: 111111
  web:
    resources:
      static-locations: file:///C:/petshop/uploads/

# 3. Mybatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 3. Log Level
logging:
  level:
    root: info   #  error < info < debug

# 4. User Define App
app:
  key:
    algo: PBEWithMD5AndDES  # Twoway
    skey: mykey             # Twoway

# 이미지 업로드 디렉토리 및 URL prefix 설정
file:
  upload:
    directory: C:/petgpt/uploads/images
    url:
      prefix: /uploads/images