# 1. Server Config
server:
  port: 8443  # HTTPS를 위한 포트 설정
  ssl:
    enabled: true
    key-store: classpath:keystore.p12  # 인증서 파일 경로 <- keystore.p12를 resource 아래 위치
    key-store-password: 111111  # 인증서 생성 시 설정한 비밀번호
    key-store-type: PKCS12  # 인증서 형식
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://118.67.143.55:3306/petgpt?characterEncoding=utf8
    username: mcuser
    password: 111111
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 3. Mybatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 4. Log Level
logging:
  level:
    root: info

# 5. User Define App
app:
  key:
    algo: PBEWithMD5AndDES
    skey: mykey
  dir:
    imgdir: /img/item/
    uploadimgdir: C:/Users/Administrator/IdeaProjects/petgpt/admin/src/main/webapp/img/item/

# 6. WebSocket 주소
  url:
    websocket-server-url: http://127.0.0.1:8088