[theme]
primaryColor = "#10a37f"  # ChatGPT의 메인 녹색
backgroundColor = "#ffffff"  # 흰색 배경
secondaryBackgroundColor = "#f7f7f8"  # ChatGPT의 메시지 배경색
textColor = "#343541"  # 어두운 텍스트 색상
font = "sans serif"

[server]
enableCORS = false

[browser]
gatherUsageStats = false 